name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set addon version
        run: |
          VERSION=${{ github.ref_name }}
          VERSION=${VERSION:1}
          find ./AI_VoiceOver -name "*.toc" -exec sed -i "s/^## Version: .*/## Version: $VERSION/" {} \;
      - name: Package WoW 1.12 addon
        run: |
          mkdir -p ./release/vanilla/AI_VoiceOver
          cp -r ./AI_VoiceOver/* ./release/vanilla/AI_VoiceOver
          cp ./release/vanilla/AI_VoiceOver/AI_VoiceOver_1.12.toc ./release/vanilla/AI_VoiceOver/AI_VoiceOver.toc

      - name: Zip WoW 1.12 release
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          cd ./release/vanilla && zip -r ../AI_VoiceOver-WoW_1.12-$VERSION.zip . && cd ../..

      - name: Generate release notes
        uses: cuchi/jinja2-action@v1.3.0
        with:
          template: .github/release-template.md
          output_file: release_notes.md
          strict: true
          variables: |
            github_zip_download_vanilla_sounds=https://github.com/mrthinger/wow-voiceover/releases/download/v1.3.1/AI_VoiceOverData_Vanilla-v1.0.0.zip
            github_zip_download_112=https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/AI_VoiceOver-WoW_1.12-${{ github.ref_name }}.zip
            curse_link_vanilla_sounds=https://www.curseforge.com/wow/addons/voiceover-sounds-vanilla
            donation_link=https://ko-fi.com/evanpierce
            discord_link=https://discord.gg/VdhUmA8ZCt

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          fail_on_unmatched_files: true
          generate_release_notes: true
          body_path: release_notes.md
          files: |
            release/AI_VoiceOver-WoW_1.12-*.zip
